name: "Yarn target determinator"
description: "Determine Yarn 2 CI build targets from changed files"

icon: target
color: red

inputs:
  files:
    description: Array of all changed files to validate, encoded as a JSON array
    required: true

outputs:
  targets:
    description: The list of Yarn workspaces to target, encoded as a JSON array

runs:
  using: "node12"
  main: "dist/index.js"
